/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bank;

/**
 *
 * @author Rizka RS
 */
public class PilihanMenu extends javax.swing.JFrame {

    /**
     * Creates new form PIN
     */
    public PilihanMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label2 = new java.awt.Label();
        button1 = new java.awt.Button();
        atm = new javax.swing.JRadioButton();
        teller = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        label2.setText("label2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        button1.setLabel("cancel");
        getContentPane().add(button1);
        button1.setBounds(70, 320, 52, 24);

        atm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        atm.setText("ATM ");
        atm.setActionCommand("atm");
        atm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atmActionPerformed(evt);
            }
        });
        getContentPane().add(atm);
        atm.setBounds(400, 160, 79, 25);

        teller.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        teller.setText("TELLER");
        teller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tellerActionPerformed(evt);
            }
        });
        getContentPane().add(teller);
        teller.setBounds(400, 190, 79, 25);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("ATAU 021-33012839");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(390, 300, 200, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Untuk Keamanan Silahkan ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 120, 200, 40);
        jLabel4.getAccessibleContext().setAccessibleName("Tutupilah dengan Jari Anda");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Tutupilah dengan Jari Anda");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 150, 200, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText(" Saat Memasukkan PIN");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 180, 200, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Tekan Cancel Untuk Batal");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 280, 200, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Pilihan Menu :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(350, 120, 200, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("MANDIRI CALL HANYA DI 14000");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(320, 280, 200, 40);

        jLabel11.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel11.setText("ATM MANDIRI PENS");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(180, 60, 240, 40);

        jLabel13.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel13.setText("SELAMAT DATANG DI");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(170, 30, 240, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bank/img.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 540, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atmActionPerformed
        // TODO add your handling code here:
        if(atm.isSelected()==true){
           new BankPIN().show();
        }
    }//GEN-LAST:event_atmActionPerformed

    private void tellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tellerActionPerformed
        // TODO add your handling code here:
        if(teller.isSelected()==true){
           new BankAdmin().show();
        }
    }//GEN-LAST:event_tellerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilihanMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton atm;
    private java.awt.Button button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private java.awt.Label label2;
    private javax.swing.JRadioButton teller;
    // End of variables declaration//GEN-END:variables
}
